<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Class CreateCategoriesTable
 */
class CreateCategoriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_categories', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->string('shop_category_name')->nullable();
            $table->string('shop_category_image_url')->nullable();
            $table->boolean('shop_category_accept_status')->nullable();
            $table->boolean('shop_category_publish_status')->nullable();
            $table->boolean( 'shop_category_show_status')->nullable();
            $table->unsignedBigInteger('shop_category_additional_user_id')->nullable();
            $table->unsignedBigInteger('shop_category_confirm_user_id')->nullable();
            $table->unsignedBigInteger('shop_category_confirm_comment_id')->nullable();
            $table->string('shop_category_confirm_comment_value')->nullable();
            $table->softDeletes();
            $table->timestamps();

            $table->foreign('parent_id')
                ->references('id')
                ->on('shop_categories')
                ->onDelete('no action')
                ->onUpdate('cascade');

            $table->foreign('shop_category_additional_user_id')
                ->references('id')
                ->on('users')
                ->onDelete('no action')
                ->onUpdate('cascade');

            $table->foreign('shop_category_confirm_user_id')
                ->references('id')
                ->on('users')
                ->onDelete('no action')
                ->onUpdate('cascade');
        });

        DB::table('shop_categories')->insert([
            [
                'id' => 1,
                'parent_id' => null,
                'shop_category_name' => 'سوپرمارکت وتره بار',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => false,
                'shop_category_publish_status' => false,
                'shop_category_show_status' => false,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 2,
                'parent_id' => null,
                'shop_category_name' => 'کافی شاپ و رستوران',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 3,
                'parent_id' => null,
                'shop_category_name' => 'ساختمان و ابزار',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 4,
                'parent_id' => null,
                'shop_category_name' => 'پوشاک و زیورآلات',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 5,
                'parent_id' => null,
                'shop_category_name' => 'لوازم منزل',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 6,
                'parent_id' => null,
                'shop_category_name' => 'دیجیتال و الکترونیک',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 7,
                'parent_id' => null,
                'shop_category_name' => 'خودرو موتورسیکلت و دوچرخه',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 8,
                'parent_id' => null,
                'shop_category_name' => 'محصولات فرهنگی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 9,
                'parent_id' => null,
                'shop_category_name' => 'آموزشی و ورزشی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 10,
                'parent_id' => null,
                'shop_category_name' => 'زیبایی پزشکی و بهداشت',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 11,
                'parent_id' => null,
                'shop_category_name' => 'دفاتر مشاوره',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 12,
                'parent_id' => null,
                'shop_category_name' => 'آذاد کاری و خود اشتغالی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 13,
                'parent_id' => 2,
                'shop_category_name' => 'رستوران',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 14,
                'parent_id' => 2,
                'shop_category_name' => 'کافه',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 15,
                'parent_id' => 2,
                'shop_category_name' => 'کافی شاپ',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 16,
                'parent_id' => 2,
                'shop_category_name' => 'فست فود و ساندویچی و فینگر فود',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 17,
                'parent_id' => 2,
                'shop_category_name' => 'آبمیوه و فروت',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 18,
                'parent_id' => 2,
                'shop_category_name' => 'آجیل فروشی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 19,
                'parent_id' => 2,
                'shop_category_name' => 'شیرینی پزی و قنادی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 20,
                'parent_id' => 3,
                'shop_category_name' => 'فروشگاه ابزار',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 21,
                'parent_id' => 3,
                'shop_category_name' => 'فروشگاه مصالح ساختمانی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 22,
                'parent_id' => 3,
                'shop_category_name' => 'فروشگاه تجهیزات صنعتی و کسب و کار',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 23,
                'parent_id' => 3,
                'shop_category_name' => 'کارگاه کابینت سازی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 24,
                'parent_id' => 3,
                'shop_category_name' => 'فروشگاه و نصاب کاغذ دیواری و رنگ',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 25,
                'parent_id' => 3,
                'shop_category_name' => 'فروشگاه و نصاب پارپپکت و پنل',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 26,
                'parent_id' => 3,
                'shop_category_name' => 'فروشگاه و نصاب کناف',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 27,
                'parent_id' => 3,
                'shop_category_name' => 'فروشگاه و نصاب برق',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 28,
                'parent_id' => 3,
                'shop_category_name' => 'فروشگاه و نصاب برق',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 29,
                'parent_id' => 3,
                'shop_category_name' => 'فروشگاه و نصاب درب و پنجره',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 30,
                'parent_id' => 3,
                'shop_category_name' => 'فروشگاه و نصاب پرده',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 31,
                'parent_id' => 3,
                'shop_category_name' => 'فروشگاه و نصاب دکوراسیون محیطی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 32,
                'parent_id' => 3,
                'shop_category_name' => 'استادکار و بنا',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 33,
                'parent_id' => 3,
                'shop_category_name' => 'تعمیر لوازم صنعتی کسب و کار',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 34,
                'parent_id' => 4,
                'shop_category_name' => 'فروشگاه لباس',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 35,
                'parent_id' => 4,
                'shop_category_name' => 'فروشگاه کیف و کفش',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 36,
                'parent_id' => 4,
                'shop_category_name' => 'فروشگاه ساعت',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 37,
                'parent_id' => 4,
                'shop_category_name' => 'فروشگاه عینک',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 38,
                'parent_id' => 4,
                'shop_category_name' => 'زیورآلات',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 39,
                'parent_id' => 4,
                'shop_category_name' => 'خیاطی (تولید و تعمیر البسه)',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 40,
                'parent_id' => 4,
                'shop_category_name' => 'تولید و تعمیر کیف و کفش',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 41,
                'parent_id' => 5,
                'shop_category_name' => 'فروشگاه ظروف آشپزخانه',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 42,
                'parent_id' => 5,
                'shop_category_name' => 'فروشگاه سرمایشی و گرمایشی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 43,
                'parent_id' => 5,
                'shop_category_name' => 'فروشگاه صوتی و تصویری',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 44,
                'parent_id' => 5,
                'shop_category_name' => 'فروشگاه و تولیدی لوازم چوبی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 45,
                'parent_id' => 5,
                'shop_category_name' => 'فروشگاه فرش و گلیم',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 46,
                'parent_id' => 5,
                'shop_category_name' => 'تعمیرات لوازم خانگی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 47,
                'parent_id' => 5,
                'shop_category_name' => 'سیسمونی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 48,
                'parent_id' => 5,
                'shop_category_name' => 'قالیشویی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 49,
                'parent_id' => 5,
                'shop_category_name' => 'کالای خواب',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 50,
                'parent_id' => 5,
                'shop_category_name' => 'نور و روشنایی و لوازم دکوری',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 51,
                'parent_id' => 6,
                'shop_category_name' => 'فروشگاه موبایل و لوازم جانبی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 52,
                'parent_id' => 6,
                'shop_category_name' => 'فروشگاه کامپیوتر و لپ تاپ',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 53,
                'parent_id' => 6,
                'shop_category_name' => 'فروشگاه و نصب دوربین مدار بسته',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 54,
                'parent_id' => 6,
                'shop_category_name' => 'فروشگاه کنسول بازی و...',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 55,
                'parent_id' => 6,
                'shop_category_name' => 'تعمیرات لوازم دیجیتال',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 56,
                'parent_id' => 7,
                'shop_category_name' => 'فروشگاه قطعات خودرو',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 57,
                'parent_id' => 7,
                'shop_category_name' => 'فروشگاه موتورسیکلت و قطعات',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 58,
                'parent_id' => 7,
                'shop_category_name' => 'فروشگاه دوچرخه و قطعات',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 59,
                'parent_id' => 7,
                'shop_category_name' => 'فروشگاه رینگ و لاستیک و تیوب',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 60,
                'parent_id' => 7,
                'shop_category_name' => 'فروشگاه تیوننیگ و سیستم صوتی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 61,
                'parent_id' => 7,
                'shop_category_name' => 'تعمیرات خودرو',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 62,
                'parent_id' => 7,
                'shop_category_name' => 'تعمیرات موتورسیکلت',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 63,
                'parent_id' => 8,
                'shop_category_name' => 'کتاب فروشی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 64,
                'parent_id' => 8,
                'shop_category_name' => 'لوازم التحریر و لازم اداری',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 65,
                'parent_id' => 8,
                'shop_category_name' => 'محصولات فرهنگی (cd و...)',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 66,
                'parent_id' => 8,
                'shop_category_name' => 'فروشگاه آلات موسیقی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 67,
                'parent_id' => 9,
                'shop_category_name' => 'زبان خارجی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 68,
                'parent_id' => 9,
                'shop_category_name' => 'تحصیلی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 69,
                'parent_id' => 9,
                'shop_category_name' => 'ورزشی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 70,
                'parent_id' => 9,
                'shop_category_name' => 'هنری',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 71,
                'parent_id' => 9,
                'shop_category_name' => 'مهارت و کسب وکار',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 72,
                'parent_id' => 10,
                'shop_category_name' => 'لوازم آرایشی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 73,
                'parent_id' => 10,
                'shop_category_name' => 'لوازم بهداشتی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 74,
                'parent_id' => 10,
                'shop_category_name' => 'عطر و ادکلن',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 75,
                'parent_id' => 10,
                'shop_category_name' => 'پیرایش آقایان',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 76,
                'parent_id' => 10,
                'shop_category_name' => 'آرایشگاه بانوان',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 77,
                'parent_id' => 10,
                'shop_category_name' => 'خدمات تخصصی زیبایی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 78,
                'parent_id' => 10,
                'shop_category_name' => 'دندانپزشکی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 79,
                'parent_id' => 10,
                'shop_category_name' => 'پت شاپ و دامپزشکی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 80,
                'parent_id' => 10,
                'shop_category_name' => 'عطاری',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 81,
                'parent_id' => 11,
                'shop_category_name' => 'وکالت',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 82,
                'parent_id' => 11,
                'shop_category_name' => 'کسب و کار',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 83,
                'parent_id' => 11,
                'shop_category_name' => 'خانواده',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 84,
                'parent_id' => 11,
                'shop_category_name' => 'تحصیلی',
                'shop_category_image_url' => null,
                'shop_category_accept_status' => true,
                'shop_category_publish_status' => true,
                'shop_category_show_status' => true,
                'shop_category_additional_user_id' => 1,
                'shop_category_confirm_user_id' => 1,
                'shop_category_confirm_comment_id' => 1,
                'shop_category_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
        ]);

//      this relation moving form migrate shop in file shop_categories
//        Schema::table('shops', function (Blueprint $table) {
//            $table->foreign('shop_category_id')
//                ->references('id')
//                ->on('shop_categories')
//                ->onDelete('no action')
//                ->onUpdate('cascade');
//        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('categories');
    }
}
