<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateWorkNatureTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('work_nature', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('subcategory_id')->nullable();
            $table->string('subcategory_name')->nullable();
            $table->string('title')->nullable();
            $table->string('work_nature')->nullable();
            $table->boolean('subcategory_accept_status')->nullable();
            $table->boolean('subcategory_publish_status')->nullable();
            $table->boolean('subcategory_show_status')->nullable();
            $table->unsignedBigInteger('subcategory_confirm_user_id')->nullable();
            $table->unsignedBigInteger('subcategory_confirm_comment_id')->nullable();
            $table->string('subcategory_confirm_comment_value')->nullable();
            $table->softDeletes();
            $table->timestamps();

            $table->foreign('subcategory_id')
                ->references('id')
                ->on('shop_categories')
                ->onDelete('no action')
                ->onUpdate('cascade');

            $table->foreign('subcategory_confirm_user_id')
                ->references('id')
                ->on('users')
                ->onDelete('no action')
                ->onUpdate('cascade');
        });

        DB::table('work_nature')->insert([
            [
                'id' => 1,
                'subcategory_id' => 13,
                'subcategory_name' => 'رستوران',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 2,
                'subcategory_id' => 14,
                'subcategory_name' => 'کافه',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 3,
                'subcategory_id' => 15,
                'subcategory_name' => 'کافی شاپ',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 4,
                'subcategory_id' => 16,
                'subcategory_name' => 'فست فود و ساندویچی و فینگر فود',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 5,
                'subcategory_id' => 17,
                'subcategory_name' => 'آبمیوه و فروت',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 6,
                'subcategory_id' => 18,
                'subcategory_name' => 'آجیل فروشی',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 7,
                'subcategory_id' => 19,
                'subcategory_name' => 'شیرینی پزی و قنادی',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 8,
                'subcategory_id' => 20,
                'subcategory_name' => 'فروشگاه ابزار',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 9,
                'subcategory_id' => 21,
                'subcategory_name' => 'فروشگاه مصالح ساختمانی',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 10,
                'subcategory_id' => 22,
                'subcategory_name' => 'فروشگاه تجهیزات صنعتی و کسب و کار',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 11,
                'subcategory_id' => 23,
                'subcategory_name' => 'کارگاه کابینت سازی',
                'title' => 'کارگاه',
                'work_nature' => 'کارگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 12,
                'subcategory_id' => 24,
                'subcategory_name' => 'فروشگاه و نصاب کاغذ دیواری و رنگ',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 13,
                'subcategory_id' => 25,
                'subcategory_name' => 'فروشگاه و نصاب پارپپکت و پنل',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 14,
                'subcategory_id' => 26,
                'subcategory_name' => 'فروشگاه و نصاب کناف',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 15,
                'subcategory_id' => 27,
                'subcategory_name' => 'فروشگاه و نصاب برق',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 16,
                'subcategory_id' => 28,
                'subcategory_name' => 'فروشگاه و نصاب برق',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 17,
                'subcategory_id' => 29,
                'subcategory_name' => 'فروشگاه و نصاب درب و پنجره',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 18,
                'subcategory_id' => 30,
                'subcategory_name' => 'فروشگاه و نصاب پرده',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 19,
                'subcategory_id' => 31,
                'subcategory_name' => 'فروشگاه و نصاب دکوراسیون محیطی',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 20,
                'subcategory_id' => 32,
                'subcategory_name' => 'استادکار و بنا',
                'title' => 'آذاد کار',
                'work_nature' => 'آذاد کار',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 21,
                'subcategory_id' => 33,
                'subcategory_name' => 'تعمیر لوازم صنعتی کسب و کار',
                'title' => 'تعمیرگاه',
                'work_nature' => 'تعمیرگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 22,
                'subcategory_id' => 33,
                'subcategory_name' => 'تعمیر لوازم صنعتی کسب و کار',
                'title' => 'تعمیرکار سیار',
                'work_nature' => 'تعمیرکار سیار',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 23,
                'subcategory_id' => 34,
                'subcategory_name' => 'فروشگاه لباس',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 24,
                'subcategory_id' => 35,
                'subcategory_name' => 'فروشگاه کیف و کفش',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 25,
                'subcategory_id' => 36,
                'subcategory_name' => 'فروشگاه ساعت',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 26,
                'subcategory_id' => 37,
                'subcategory_name' => 'فروشگاه عینک',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 27,
                'subcategory_id' => 38,
                'subcategory_name' => 'زیورآلات',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 28,
                'subcategory_id' => 39,
                'subcategory_name' => 'خیاطی (تولید و تعمیر البسه)',
                'title' => 'تولیدی',
                'work_nature' => 'تولیدی',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 29,
                'subcategory_id' => 39,
                'subcategory_name' => 'خیاطی (تولید و تعمیر البسه)',
                'title' => 'تعمیرکار سیار',
                'work_nature' => 'تعمیرکار سیار',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 30,
                'subcategory_id' => 40,
                'subcategory_name' => 'تولید و تعمیر کیف و کفش',
                'title' => 'تولیدی',
                'work_nature' => 'تولیدی',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 31,
                'subcategory_id' => 40,
                'subcategory_name' => 'تولید و تعمیر کیف و کفش',
                'title' => 'کفاشی',
                'work_nature' => 'کفاشی',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 32,
                'subcategory_id' => 41,
                'subcategory_name' => 'فروشگاه ظروف آشپزخانه',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 33,
                'subcategory_id' => 42,
                'subcategory_name' => 'فروشگاه سرمایشی و گرمایشی',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 34,
                'subcategory_id' => 43,
                'subcategory_name' => 'فروشگاه صوتی و تصویری',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 35,
                'subcategory_id' => 44,
                'subcategory_name' => 'فروشگاه و تولیدی لوازم چوبی',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 36,
                'subcategory_id' => 45,
                'subcategory_name' => 'فروشگاه فرش و گلیم',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 37,
                'subcategory_id' => 46,
                'subcategory_name' => 'تعمیرات لوازم خانگی',
                'title' => 'تعمیرگاه',
                'work_nature' => 'تعمیرگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 38,
                'subcategory_id' => 46,
                'subcategory_name' => 'تعمیرات لوازم خانگی',
                'title' => 'تعمیرکار سیار',
                'work_nature' => 'تعمیرکار سیار',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 39,
                'subcategory_id' => 47,
                'subcategory_name' => 'سیسمونی',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 40,
                'subcategory_id' => 48,
                'subcategory_name' => 'قالیشویی',
                'title' => 'کارگاه قالیشویی',
                'work_nature' => 'کارگاه قالیشویی',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 41,
                'subcategory_id' => 48,
                'subcategory_name' => 'قالیشویی',
                'title' => 'قالیشویی سیار',
                'work_nature' => 'قالیشویی سیار',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 42,
                'subcategory_id' => 49,
                'subcategory_name' => 'کالای خواب',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 43,
                'subcategory_id' => 50,
                'subcategory_name' => 'نور و روشنایی و لوازم دکوری',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 44,
                'subcategory_id' => 51,
                'subcategory_name' => 'فروشگاه موبایل و لوازم جانبی',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 45,
                'subcategory_id' => 52,
                'subcategory_name' => 'فروشگاه کامپیوتر و لپ تاپ',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 46,
                'subcategory_id' => 53,
                'subcategory_name' => 'فروشگاه و نصب دوربین مدار بسته',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 47,
                'subcategory_id' => 54,
                'subcategory_name' => 'فروشگاه کنسول بازی و...',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 48,
                'subcategory_id' => 55,
                'subcategory_name' => 'تعمیرات لوازم دیجیتال',
                'title' => 'تعمیرگاه',
                'work_nature' => 'تعمیرگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 49,
                'subcategory_id' => 55,
                'subcategory_name' => 'تعمیرات لوازم دیجیتال',
                'title' => 'تعمیرکار سیار',
                'work_nature' => 'تعمیرکار سیار',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 50,
                'subcategory_id' => 56,
                'subcategory_name' => 'فروشگاه قطعات خودرو',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 51,
                'subcategory_id' => 57,
                'subcategory_name' => 'فروشگاه موتورسیکلت و قطعات',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 52,
                'subcategory_id' => 58,
                'subcategory_name' => 'فروشگاه دوچرخه و قطعات',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 53,
                'subcategory_id' => 59,
                'subcategory_name' => 'فروشگاه رینگ و لاستیک و تیوب',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 54,
                'subcategory_id' => 60,
                'subcategory_name' => 'فروشگاه تیوننیگ و سیستم صوتی',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 55,
                'subcategory_id' => 61,
                'subcategory_name' => 'تعمیرات خودرو',
                'title' => 'تعمیرگاه',
                'work_nature' => 'تعمیرگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 56,
                'subcategory_id' => 61,
                'subcategory_name' => 'تعمیرات خودرو',
                'title' => 'تعمیرکار سیار',
                'work_nature' => 'تعمیرکار سیار',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 57,
                'subcategory_id' => 62,
                'subcategory_name' => 'تعمیرات موتورسیکلت',
                'title' => 'تعمیرگاه',
                'work_nature' => 'تعمیرگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 58,
                'subcategory_id' => 62,
                'subcategory_name' => 'تعمیرات موتورسیکلت',
                'title' => 'تعمیرکار سیار',
                'work_nature' => 'تعمیرکار سیار',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 59,
                'subcategory_id' => 63,
                'subcategory_name' => 'کتاب فروشی',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 60,
                'subcategory_id' => 64,
                'subcategory_name' => 'لوازم التحریر و لازم اداری',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 61,
                'subcategory_id' => 65,
                'subcategory_name' => 'محصولات فرهنگی (cd و...)',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 62,
                'subcategory_id' => 66,
                'subcategory_name' => 'فروشگاه آلات موسیقی',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 63,
                'subcategory_id' => 67,
                'subcategory_name' => 'زبان خارجی',
                'title' => 'آموزشگاه',
                'work_nature' => 'آموزشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 64,
                'subcategory_id' => 67,
                'subcategory_name' => 'زبان خارجی',
                'title' => 'مدرس',
                'work_nature' => 'مدرس',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 65,
                'subcategory_id' => 68,
                'subcategory_name' => 'تحصیلی',
                'title' => 'آموزشگاه',
                'work_nature' => 'آموزشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 66,
                'subcategory_id' => 68,
                'subcategory_name' => 'تحصیلی',
                'title' => 'مدرس',
                'work_nature' => 'مدرس',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 67,
                'subcategory_id' => 69,
                'subcategory_name' => 'ورزشی',
                'title' => 'باشگاه',
                'work_nature' => 'باشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 68,
                'subcategory_id' => 69,
                'subcategory_name' => 'ورزشی',
                'title' => 'مربی',
                'work_nature' => 'مربی',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 69,
                'subcategory_id' => 70,
                'subcategory_name' => 'هنری',
                'title' => 'اموزشگاه - آتلیه',
                'work_nature' => 'اموزشگاه - آتلیه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 70,
                'subcategory_id' => 70,
                'subcategory_name' => 'هنری',
                'title' => 'مربی',
                'work_nature' => 'مربی',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 71,
                'subcategory_id' => 71,
                'subcategory_name' => 'مهارت و کسب وکار',
                'title' => 'اموزشگاه',
                'work_nature' => 'اموزشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 72,
                'subcategory_id' => 71,
                'subcategory_name' => 'مهارت و کسب وکار',
                'title' => 'مربی',
                'work_nature' => 'مربی',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 73,
                'subcategory_id' => 72,
                'subcategory_name' => 'لوازم آرایشی',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 74,
                'subcategory_id' => 73,
                'subcategory_name' => 'لوازم بهداشتی',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 75,
                'subcategory_id' => 74,
                'subcategory_name' => 'عطر و ادکلن',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 76,
                'subcategory_id' => 75,
                'subcategory_name' => 'پیرایش آقایان',
                'title' => 'آرایشگاه',
                'work_nature' => 'آرایشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 77,
                'subcategory_id' => 75,
                'subcategory_name' => 'پیرایش آقایان',
                'title' => 'آرایشگر سیار',
                'work_nature' => 'آرایشگر سیار',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 78,
                'subcategory_id' => 76,
                'subcategory_name' => 'آرایشگاه بانوان',
                'title' => 'آرایشگاه',
                'work_nature' => 'آرایشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 79,
                'subcategory_id' => 76,
                'subcategory_name' => 'آرایشگاه بانوان',
                'title' => 'آرایشگر سیار',
                'work_nature' => 'آرایشگر سیار',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 80,
                'subcategory_id' => 77,
                'subcategory_name' => 'خدمات تخصصی زیبایی',
                'title' => 'سالن زیبایی',
                'work_nature' => 'سالن زیبایی',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 81,
                'subcategory_id' => 77,
                'subcategory_name' => 'خدمات تخصصی زیبایی',
                'title' => 'خدمات سیار',
                'work_nature' => 'خدمات سیار',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 82,
                'subcategory_id' => 78,
                'subcategory_name' => 'دندانپزشکی',
                'title' => 'کلینیک',
                'work_nature' => 'کلینیک',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 83,
                'subcategory_id' => 79,
                'subcategory_name' => 'پت شاپ و دامپزشکی',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 84,
                'subcategory_id' => 79,
                'subcategory_name' => 'پت شاپ و دامپزشکی',
                'title' => 'کلینیک',
                'work_nature' => 'کلینیک',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 85,
                'subcategory_id' => 80,
                'subcategory_name' => 'عطاری',
                'title' => 'فروشگاه',
                'work_nature' => 'فروشگاه',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 86,
                'subcategory_id' => 81,
                'subcategory_name' => 'وکالت',
                'title' => 'دفتری',
                'work_nature' => 'دفتری',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 87,
                'subcategory_id' => 82,
                'subcategory_name' => 'کسب و کار',
                'title' => 'دفتری',
                'work_nature' => 'دفتری',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 88,
                'subcategory_id' => 83,
                'subcategory_name' => 'خانواده',
                'title' => 'دفتری',
                'work_nature' => 'دفتری',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
            [
                'id' => 89,
                'subcategory_id' => 84,
                'subcategory_name' => 'تحصیلی',
                'title' => 'دفتری',
                'work_nature' => 'دفتری',
                'subcategory_accept_status' => true,
                'subcategory_publish_status' => true,
                'subcategory_show_status' => true,
                'subcategory_confirm_user_id' => 1,
                'subcategory_confirm_comment_id' => 1,
                'subcategory_confirm_comment_value' => 'تایید شد',
                'created_at' => '2021-08-07 04:41:40',
                'updated_at' => '2021-08-07 04:41:40'
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('work_nature');
    }
}
